# Generated by Django 6.0.6 on 2026-06-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AulaPratica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('observacoes', models.TextField(blank=True)),
                ('percurso', models.CharField(max_length=400)),
                ('presenca', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AulaTeorica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('observacoes', models.TextField(blank=True)),
                ('tema', models.CharField(max_length=200)),
                ('presenca', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamePratico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('observacoes', models.TextField(blank=True)),
                ('faltas', models.PositiveIntegerField(default=0)),
                ('resultado', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExameTeorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('observacoes', models.TextField(blank=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('resultado', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
