# Generated by Django 6.0.6 on 2026-06-19 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habilita', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aulapratica',
            options={'verbose_name': 'Aula Prática', 'verbose_name_plural': 'Aulas Práticas'},
        ),
        migrations.AlterModelOptions(
            name='aulateorica',
            options={'verbose_name': 'Aula Teórica', 'verbose_name_plural': 'Aulas Teóricas'},
        ),
        migrations.AlterModelOptions(
            name='examepratico',
            options={'verbose_name': 'Exame Prático', 'verbose_name_plural': 'Exames Práticos'},
        ),
        migrations.AlterModelOptions(
            name='exameteorico',
            options={'verbose_name': 'Exame Teórico', 'verbose_name_plural': 'Exames Teóricos'},
        ),
    ]
